# pylint: disable=too-many-lines
AD_STATUS_NEW = 'new'
AD_STATUS_DISAPPROVED = 'disapproved'
AD_STATUS_CHOICES = [
    (AD_STATUS_NEW, 'New'),
    ('submitted', 'Submitted'),
    ('approved', 'Approved'),
    (AD_STATUS_DISAPPROVED, 'Disapproved'),
]

A9_STATUS_PASSED = 'passed'
A9_STATUS_PENDING = 'pending'
A9_STATUS_FAILED = 'failed'
A9_STATUS_CHOICES = [
    (A9_STATUS_PASSED, 'Passed'),
    (A9_STATUS_PENDING, 'Pending'),
    (A9_STATUS_FAILED, 'Failed'),
]

CURRENCY_USD = 'USD'
CURRENCY_CHOICES = [
    (CURRENCY_USD, 'USD'),
    ('CAD', 'CAD'),
]

GENDER_CHOICES = [
    ('', 'Any'),
    ('m', 'Males'),
    ('f', 'Females'),
]

NETWORK_SPEED_CHOICES = [
    ('', ''),
    ('cellular', 'Cellular only'),
    ('wifi', 'Wi-Fi only'),
]

CLASS_CHOICES = [
    ('', ''),
    ('social', 'Social'),
    ('mobile', 'Mobile'),
]

SIZE_CHOICES = [
    ('all', 'all'),
    ('0x0', '0x0'),
    ('300x250', '300x250'),
    ('320x50', '320x50'),
    ('240x350', '240x350'),
    ('390x200', '390x200'),
    ('320x480', '320x480'),
    ('480x320', '480x320'),
    ('560x750', '560x750'),
    ('750x560', '750x560'),
    ('728x90', '728x90'),
    ('768x1024', '768x1024'),
    ('1024x768', '1024x768'),
    ('480x800', '480x800'),
    ('800x480', '800x480'),
    ('468x60', '468x60'),
    ('336x280', '336x280'),
    ('375x50', '375x50'),
]

CUSTOM_HINT_SIZE_CHOICES = [
    ('all', 'all'),
    ('0x0', '0x0'),
    ('300x250', '300x250'),
    ('320x50', '320x50'),
    ('240x350', '240x350'),
    ('390x200', '390x200'),
    ('320x480', '320x480'),
    ('480x320', '480x320'),
    ('560x750', '560x750'),
    ('750x560', '750x560'),
    ('728x90', '728x90'),
    ('768x1024', '768x1024'),
    ('1024x768', '1024x768'),
    ('480x800', '480x800'),
    ('800x480', '800x480'),
    ('468x60', '468x60'),
    ('336x280', '336x280'),
    ('375x50', '375x50'),
]
DISCRETE_PRICING_SIZE_CHOICES = CUSTOM_HINT_SIZE_CHOICES

AD_SIZE_CHOICES = [
    ('0x0', '0x0'),
    ('300x250', '300x250'),
    ('320x50', '320x50'),
    ('240x350', '240x350'),
    ('390x200', '390x200'),
    ('320x480', '320x480'),
    ('480x320', '480x320'),
    ('560x750', '560x750'),
    ('750x560', '750x560'),
    ('720x90', '720x90'),
    ('728x90', '728x90'),
    ('768x1024', '768x1024'),
    ('1024x768', '1024x768'),
    ('480x800', '480x800'),
    ('800x480', '800x480'),
    ('468x60', '468x60'),
    ('336x280', '336x280'),
    ('375x50', '375x50'),
    ('160x160', '160x160'),
]

SIZE_ALL = SIZE_CHOICES[0][0]

STATUS_ENABLED = 'enabled'
STATUS_PAUSED = 'paused'
STATUS_ARCHIVED = 'deleted'
STATUS_CHOICES = [
    (STATUS_ENABLED, 'Enabled'),
    (STATUS_PAUSED, 'Paused'),
    (STATUS_ARCHIVED, 'Archived'),
]

PLACEMENT_TYPE_CHOICES = (
    ('app', 'Application'),
    ('site', 'Site'),
)
PLACEMENT_TYPE_ALL = PLACEMENT_TYPE_CHOICES[0][0]

PUBLISHER_STATUS_CHOICES = (
    ('unapproved', 'Unapproved'),
    ('approved', 'Approved'),
    ('disabled', 'Disabled'),
    ('deleted', 'Deleted'),
)
PUBLISHER_STATUS_APPROVED = PUBLISHER_STATUS_CHOICES[1][0]

AD_GROUP_TYPE_CHOICES = [
    (1, 'Display and Richmedia'),
    (3, 'Experience'),
    (4, 'MRAID'),
    (5, 'Native'),
    (0, ''),
    (2, 'Video'),
]

AD_TYPE_CHOICES = [
    (0, ''),
    (1, 'Display'),
    (2, 'Vast'),
    (3, 'Voxel'),
    (4, 'MRAID'),
    (5, 'Native'),
    (6, 'Richmedia'),
]
AD_TYPE_NONE = AD_TYPE_CHOICES[0][0]
AD_TYPE_DISPLAY = AD_TYPE_CHOICES[1][0]
AD_TYPE_VIDEO = AD_TYPE_CHOICES[2][0]
AD_TYPE_MRAID = AD_TYPE_CHOICES[4][0]
AD_TYPE_NATIVE = AD_TYPE_CHOICES[5][0]
AD_TYPE_RICHMEDIA = AD_TYPE_CHOICES[6][0]

BUDGET_TYPES_CHOICES = [
    ('', ''),
    ('cost', 'Cost'),
    ('revenue', 'Revenue'),
    ('impression', 'Impression'),
    ('click', 'Click'),
    ('install', 'Install'),
]

OPT_TYPE_CHOICES = [
    ('impression', 'Impression'),
    ('view', 'View'),
    ('click', 'Click'),
    ('install', 'Install'),
    ('event', 'Event'),
    ('cost_plus', 'costPlus'),
    ('post_install', 'postInstall'),
]

INFLATOR_TYPE_CHOICES = [
    ('NULL', 'NULL'),
    ('absolute', 'Absolute'),
    ('relative', ' Relative'),
]

INFLATOR_SOURCES = [
    ('*', 'All'),
    ('A9', 'A9'),
    ('Adfonic', 'Adfonic'),
    ('AdIQuity', 'AdIQuity'),
    ('Admeld', 'Admeld'),
    ('Admob', 'Admob'),
    ('AdRoll', 'AdRoll'),
    ('Adwhirl', 'Adwhirl'),
    ('AdWords', 'AdWords'),
    ('AdX', 'AdX'),
    ('AerServ', 'AerServ'),
    ('Appbank', 'Appbank'),
    ('AppNexus', 'AppNexus'),
    ('AppSponsor', 'AppSponsor'),
    ('BrightRoll', 'BrightRoll'),
    ('Burstly', 'Burstly'),
    ('Facebook', 'Facebook'),
    ('Flurry', 'Flurry'),
    ('GoMobileGames', 'GoMobileGames'),
    ('Inmobi', 'Inmobi'),
    ('Inneractive', 'Inneractive'),
    ('Jumptap', 'Jumptap'),
    ('Jumpramp', 'Jumpramp'),
    ('LiveRail', 'LiveRail'),
    ('Millennial Media', 'Millennial Media'),
    ('Mobage', 'Mobage'),
    ('Mobclix', 'Mobclix'),
    ('Mobfox', 'Mobfox'),
    ('Mojiva', 'Mojiva'),
    ('Mopub', 'Mopub'),
    ('Nexage', 'Nexage'),
    ('Openx', 'Openx'),
    ('Opera', 'Opera'),
    ('Pandora', 'Pandora'),
    ('Pubmatic', 'Pubmatic'),
    ('Rubicon', 'Rubicon'),
    ('Smaato', 'Smaato'),
    ('StApps', 'StApps'),
    ('Tapsense', 'Tapsense'),
    ('Test', 'Test'),
]

FREQUENCY_SOURCES = [
    ('*', 'Any'),
    ('300x250', '300x250'),
    ('320x50', '320x50'),
    ('375x50', '375x50'),
    ('240x350', '240x350'),
    ('390x200', '390x200'),
    ('560x750', '560x750'),
    ('750x560', '750x560'),
    ('728x90', '728x90'),
    ('480x800', '480x800'),
    ('800x480', '800x480'),
    ('468x60', '468x60'),
    ('336x280', '336x280'),
    ('320x480', '320x480'),
    ('480x320', '480x320'),
    ('768x1024', '768x1024'),
    ('1024x768', '1024x768'),
    ('0x0', '0x0'),
]
IAB_CATEGORIES = [
    ('IAB1', 'Arts & Entertainment'),
    ('IAB1-1', 'Books & Literature'),
    ('IAB1-2', 'Celebrity Fan/Gossip'),
    ('IAB1-3', 'Fine Art'),
    ('IAB1-4', 'Humor'),
    ('IAB1-5', 'Movies'),
    ('IAB1-6', 'Music'),
    ('IAB1-7', 'Television'),
    ('IAB2', 'Automotive'),
    ('IAB2-1', 'Auto Parts'),
    ('IAB2-2', 'Auto Repair'),
    ('IAB2-3', 'Buying/Selling Cars'),
    ('IAB2-4', 'Car Culture'),
    ('IAB2-5', 'Certified Pre-Owned'),
    ('IAB2-6', 'Convertible'),
    ('IAB2-7', 'Coupe'),
    ('IAB2-8', 'Crossover'),
    ('IAB2-9', 'Diesel'),
    ('IAB2-10', 'Electric Vehicle'),
    ('IAB2-11', 'Hatchback'),
    ('IAB2-12', 'Hybrid'),
    ('IAB2-13', 'Luxury'),
    ('IAB2-14', 'MiniVan'),
    ('IAB2-15', 'Mororcycles'),
    ('IAB2-16', 'Off-Road Vehicles'),
    ('IAB2-17', 'Performance Vehicles'),
    ('IAB2-18', 'Pickup'),
    ('IAB2-19', 'Road-Side Assistance'),
    ('IAB2-20', 'Sedan'),
    ('IAB2-21', 'Trucks & Accessories'),
    ('IAB2-22', 'Vintage Cars'),
    ('IAB2-23', 'Wagon'),
    ('IAB3', 'Business'),
    ('IAB3-1', 'Advertising'),
    ('IAB3-2', 'Agriculture'),
    ('IAB3-3', 'Biotech/Biomedical'),
    ('IAB3-4', 'Business Software'),
    ('IAB3-5', 'Construction'),
    ('IAB3-6', 'Forestry'),
    ('IAB3-7', 'Government'),
    ('IAB3-8', 'Green Solutions'),
    ('IAB3-9', 'Human Resources'),
    ('IAB3-10', 'Logistics'),
    ('IAB3-11', 'Marketing'),
    ('IAB3-12', 'Metals'),
    ('IAB4', 'Careers'),
    ('IAB4-1', 'Career Planning'),
    ('IAB4-2', 'College'),
    ('IAB4-3', 'Financial Aid'),
    ('IAB4-4', 'Job Fairs'),
    ('IAB4-5', 'Job Search'),
    ('IAB4-6', 'Resume Writing/Advice'),
    ('IAB4-7', 'Nursing'),
    ('IAB4-8', 'Scholarships'),
    ('IAB4-9', 'Telecommuting'),
    ('IAB4-10', 'U.S. Military'),
    ('IAB4-11', 'Career Advice'),
    ('IAB5', 'Education'),
    ('IAB5-1', '7-12 Education'),
    ('IAB5-2', 'Adult Education'),
    ('IAB5-3', 'Art History'),
    ('IAB5-4', 'Colledge Administration'),
    ('IAB5-5', 'College Life'),
    ('IAB5-6', 'Distance Learning'),
    ('IAB5-7', 'English as a 2nd Language'),
    ('IAB5-8', 'Language Learning'),
    ('IAB5-9', 'Graduate School'),
    ('IAB5-10', 'Homeschooling'),
    ('IAB5-11', 'Homework/Study Tips'),
    ('IAB5-12', 'K-6 Educators'),
    ('IAB5-13', 'Private School'),
    ('IAB5-14', 'Special Education'),
    ('IAB5-15', 'Studying Business'),
    ('IAB6', 'Family & Parenting'),
    ('IAB6-1', 'Adoption'),
    ('IAB6-2', 'Babies & Toddlers'),
    ('IAB6-3', 'Daycare/Pre School'),
    ('IAB6-4', 'Family Internet'),
    ('IAB6-5', 'Parenting - K-6 Kids'),
    ('IAB6-6', 'Parenting teens'),
    ('IAB6-7', 'Pregnancy'),
    ('IAB6-8', 'Special Needs Kids'),
    ('IAB6-9', 'Eldercare'),
    ('IAB7', 'Health & Fitness'),
    ('IAB7-1', 'Exercise'),
    ('IAB7-2', 'A.D.D.'),
    ('IAB7-3', 'AIDS/HIV'),
    ('IAB7-4', 'Allergies'),
    ('IAB7-5', 'Alternative Medicine'),
    ('IAB7-6', 'Arthritis'),
    ('IAB7-7', 'Asthma'),
    ('IAB7-8', 'Autism/PDD'),
    ('IAB7-9', 'Bipolar Disorder'),
    ('IAB7-10', 'Brain Tumor'),
    ('IAB7-11', 'Cancer'),
    ('IAB7-12', 'Cholesterol'),
    ('IAB7-13', 'Chronic Fatigue Syndrome'),
    ('IAB7-14', 'Chronic Pain'),
    ('IAB7-15', 'Cold & Flu'),
    ('IAB7-16', 'Deafness'),
    ('IAB7-17', 'Dental Care'),
    ('IAB7-18', 'Depression'),
    ('IAB7-19', 'Dermatology'),
    ('IAB7-20', 'Diabetes'),
    ('IAB7-21', 'Epilepsy'),
    ('IAB7-22', 'GERD/Acid Reflux'),
    ('IAB7-23', 'Headaches/Migraines'),
    ('IAB7-24', 'Heart Disease'),
    ('IAB7-25', 'Herbs for Health'),
    ('IAB7-26', 'Holistic Healing'),
    ('IAB7-27', 'IBS/Crohn\'s Disease'),
    ('IAB7-28', 'Incest/Abuse Support'),
    ('IAB7-29', 'Incontinence'),
    ('IAB7-30', 'Infertility'),
    ('IAB7-31', 'Men\'s Health'),
    ('IAB7-32', 'Nutrition'),
    ('IAB7-33', 'Orthopedics'),
    ('IAB7-34', 'Panic/Anxiety Disorders'),
    ('IAB7-35', 'Pediatrics'),
    ('IAB7-36', 'Physical Therapy'),
    ('IAB7-37', 'Psychology/Psychiatry'),
    ('IAB7-38', 'Senor Health'),
    ('IAB7-39', 'Sexuality'),
    ('IAB7-40', 'Sleep Disorders'),
    ('IAB7-41', 'Smoking Cessation'),
    ('IAB7-42', 'Substance Abuse'),
    ('IAB7-43', 'Thyroid Disease'),
    ('IAB7-44', 'Weight Loss'),
    ('IAB7-45', 'Women\'s Health'),
    ('IAB8', 'Food & Drink'),
    ('IAB8-1', 'American Cuisine'),
    ('IAB8-2', 'Barbecues & Grilling'),
    ('IAB8-3', 'Cajun/Creole'),
    ('IAB8-4', 'Chinese Cuisine'),
    ('IAB8-5', 'Cocktails/Beer'),
    ('IAB8-6', 'Coffee/Tea'),
    ('IAB8-7', 'Cuisine-Specific'),
    ('IAB8-8', 'Desserts & Baking'),
    ('IAB8-9', 'Dining Out'),
    ('IAB8-10', 'Food Allergies'),
    ('IAB8-11', 'French Cuisine'),
    ('IAB8-12', 'Health/Lowfat Cooking'),
    ('IAB8-13', 'Italian Cuisine'),
    ('IAB8-14', 'Japanese Cuisine'),
    ('IAB8-15', 'Mexican Cuisine'),
    ('IAB8-16', 'Vegan'),
    ('IAB8-17', 'Vegetarian'),
    ('IAB8-18', 'Wine'),
    ('IAB9', 'Hobbies & Interests'),
    ('IAB9-1', 'Art/Technology'),
    ('IAB9-2', 'Arts & Crafts'),
    ('IAB9-3', 'Beadwork'),
    ('IAB9-4', 'Birdwatching'),
    ('IAB9-5', 'Board Games/Puzzles'),
    ('IAB9-6', 'Candle & Soap Making'),
    ('IAB9-7', 'Card Games'),
    ('IAB9-8', 'Chess'),
    ('IAB9-9', 'Cigars'),
    ('IAB9-10', 'Collecting'),
    ('IAB9-11', 'Comic Books'),
    ('IAB9-12', 'Drawing/Sketching'),
    ('IAB9-13', 'Freelance Writing'),
    ('IAB9-14', 'Genealogy'),
    ('IAB9-15', 'Getting Published'),
    ('IAB9-16', 'Guitar'),
    ('IAB9-17', 'Home Recording'),
    ('IAB9-18', 'Investors & Patents'),
    ('IAB9-19', 'Jewelry Making'),
    ('IAB9-20', 'Magic & Illusion'),
    ('IAB9-21', 'Needlework'),
    ('IAB9-22', 'Painting'),
    ('IAB9-23', 'Photography'),
    ('IAB9-24', 'Radio'),
    ('IAB9-25', 'Roleplaying Games'),
    ('IAB9-26', 'Sci-Fi & Fantasy'),
    ('IAB9-27', 'Scrapbooking'),
    ('IAB9-28', 'Screenwriting'),
    ('IAB9-29', 'Stamps & Coins'),
    ('IAB9-30', 'Video & Computer Games'),
    ('IAB9-31', 'Woodworking'),
    ('IAB10', 'Home & Garden'),
    ('IAB10-1', 'Appliances'),
    ('IAB10-2', 'Entertaining'),
    ('IAB10-3', 'Environmental Safety'),
    ('IAB10-4', 'Gardening'),
    ('IAB10-5', 'Home Repair'),
    ('IAB10-6', 'Home Theater'),
    ('IAB10-7', 'Interior Decorating'),
    ('IAB10-8', 'Landscaping'),
    ('IAB10-9', 'Remodeling & Construction'),
    ('IAB11', 'Law, Gov\'t & Politics'),
    ('IAB11-1', 'Immigration'),
    ('IAB11-2', 'Legal Issues'),
    ('IAB11-3', 'U.S. Government Resources'),
    ('IAB11-4', 'Politics'),
    ('IAB11-5', 'Commentary'),
    ('IAB12', 'News'),
    ('IAB12-1', 'International News'),
    ('IAB12-2', 'National News'),
    ('IAB12-3', 'Local News'),
    ('IAB13', 'Personal Finance'),
    ('IAB13-1', 'Beginning Investing'),
    ('IAB13-2', 'Credit/Debt & Loans'),
    ('IAB13-3', 'Financial News'),
    ('IAB13-4', 'Financial Planning'),
    ('IAB13-5', 'Hedge Fund'),
    ('IAB13-6', 'Insurance'),
    ('IAB13-7', 'Investing'),
    ('IAB13-8', 'Mutual Funds'),
    ('IAB13-9', 'Options'),
    ('IAB13-10', 'Retirement Planning'),
    ('IAB13-11', 'Stocks'),
    ('IAB13-12', 'Tax Planning'),
    ('IAB14', 'Society'),
    ('IAB14-1', 'Dating'),
    ('IAB14-2', 'Divorce Support'),
    ('IAB14-3', 'Gay Life'),
    ('IAB14-4', 'Marriage'),
    ('IAB14-5', 'Senior Living'),
    ('IAB14-6', 'Teens'),
    ('IAB14-7', 'Weddings'),
    ('IAB14-8', 'Ethnic Specific'),
    ('IAB15', 'Science'),
    ('IAB15-1', 'Astrology'),
    ('IAB15-2', 'Biology'),
    ('IAB15-3', 'Chemistry'),
    ('IAB15-4', 'Geology'),
    ('IAB15-5', 'Paranormal Phenomena'),
    ('IAB15-6', 'Physics'),
    ('IAB15-7', 'Space/Astronomy'),
    ('IAB15-8', 'Geography'),
    ('IAB15-9', 'Botany'),
    ('IAB15-10', 'Weather'),
    ('IAB16', 'Pets'),
    ('IAB16-1', 'Aquariums'),
    ('IAB16-2', 'Birds'),
    ('IAB16-3', 'Cats'),
    ('IAB16-4', 'Dogs'),
    ('IAB16-5', 'Large Animals'),
    ('IAB16-6', 'Reptiles'),
    ('IAB16-7', 'Veterinary Medicine'),
    ('IAB17', 'Sports'),
    ('IAB17-1', 'Auto Racing'),
    ('IAB17-2', 'Baseball'),
    ('IAB17-3', 'Bicycling'),
    ('IAB17-4', 'Bodybuilding'),
    ('IAB17-5', 'Boxing'),
    ('IAB17-6', 'Canoeing/Kayaking'),
    ('IAB17-7', 'Cheerleading'),
    ('IAB17-8', 'Climbing'),
    ('IAB17-9', 'Cricket'),
    ('IAB17-10', 'Figure Skating'),
    ('IAB17-11', 'Fly Fishing'),
    ('IAB17-12', 'Football'),
    ('IAB17-13', 'Freshwater Fishing'),
    ('IAB17-14', 'Game & Fish'),
    ('IAB17-15', 'Golf'),
    ('IAB17-16', 'Horse Racing'),
    ('IAB17-17', 'Horses'),
    ('IAB17-18', 'Hunting/Shooting'),
    ('IAB17-19', 'Inline Skating'),
    ('IAB17-20', 'Martial Arts'),
    ('IAB17-21', 'Mountain Biking'),
    ('IAB17-22', 'NASCAR Racing'),
    ('IAB17-23', 'Olympics'),
    ('IAB17-24', 'Paintball'),
    ('IAB17-25', 'Power & Motorcycles'),
    ('IAB17-26', 'Pro Basketball'),
    ('IAB17-27', 'Pro Ice Hockey'),
    ('IAB17-28', 'Rodeo'),
    ('IAB17-29', 'Rugby'),
    ('IAB17-30', 'Running/Jogging'),
    ('IAB17-31', 'Sailing'),
    ('IAB17-32', 'Saltwater Fishing'),
    ('IAB17-33', 'Scuba Diving'),
    ('IAB17-34', 'Skateboarding'),
    ('IAB17-35', 'Skiing'),
    ('IAB17-36', 'Snowboarding'),
    ('IAB17-37', 'Surfing/Bodyboarding'),
    ('IAB17-38', 'Swimming'),
    ('IAB17-39', 'Table Tennis/Ping-Pong'),
    ('IAB17-40', 'Tennis'),
    ('IAB17-41', 'Volleyball'),
    ('IAB17-42', 'Walking'),
    ('IAB17-43', 'Waterski/Wakeboard'),
    ('IAB17-44', 'World Soccer'),
    ('IAB18', 'Style & Fashion'),
    ('IAB18-1', 'Beauty'),
    ('IAB18-2', 'Body Art'),
    ('IAB18-3', 'Fashion'),
    ('IAB18-4', 'Jewelry'),
    ('IAB18-5', 'Clothing'),
    ('IAB18-6', 'Accessories'),
    ('IAB19', 'Technology & Computing'),
    ('IAB19-1', '3-D Graphics'),
    ('IAB19-2', 'Animation'),
    ('IAB19-3', 'Antivirus Software'),
    ('IAB19-4', 'C/C++'),
    ('IAB19-5', 'Cameras & Camcorders'),
    ('IAB19-6', 'Cell Phones'),
    ('IAB19-7', 'Computer Certification'),
    ('IAB19-8', 'Computer Networking'),
    ('IAB19-9', 'Computer Peripherals'),
    ('IAB19-10', 'Computer Reviews'),
    ('IAB19-11', 'Data Centers'),
    ('IAB19-12', 'Databases'),
    ('IAB19-13', 'Desktop Publishing'),
    ('IAB19-14', 'Desktop Video'),
    ('IAB19-15', 'Email'),
    ('IAB19-16', 'Graphics Software'),
    ('IAB19-17', 'Home Video/DVD'),
    ('IAB19-18', 'Internet Technology'),
    ('IAB19-19', 'Java'),
    ('IAB19-20', 'JavaScript'),
    ('IAB19-21', 'Mac Support'),
    ('IAB19-22', 'MP3/MIDI'),
    ('IAB19-23', 'Net Conferencing'),
    ('IAB19-24', 'Net for Beginners'),
    ('IAB19-25', 'Network Security'),
    ('IAB19-26', 'Palmtops/PDAs'),
    ('IAB19-27', 'PC Support'),
    ('IAB19-28', 'Portable'),
    ('IAB19-29', 'Entertainment'),
    ('IAB19-30', 'Shareware/Freeware'),
    ('IAB19-31', 'Unix'),
    ('IAB19-32', 'Visual Basic'),
    ('IAB19-33', 'Web Clip Art'),
    ('IAB19-34', 'Web Design/HTML'),
    ('IAB19-35', 'Web Search'),
    ('IAB19-36', 'Windows'),
    ('IAB20', 'Travel'),
    ('IAB20-1', 'Adventure Travel'),
    ('IAB20-2', 'Africa'),
    ('IAB20-3', 'Air Travel'),
    ('IAB20-4', 'Australia & New Zealand'),
    ('IAB20-5', 'Bed & Breakfasts'),
    ('IAB20-6', 'Budget Travel'),
    ('IAB20-7', 'Business Travel'),
    ('IAB20-8', 'By US Locale'),
    ('IAB20-9', 'Camping'),
    ('IAB20-10', 'Canada'),
    ('IAB20-11', 'Caribbean'),
    ('IAB20-12', 'Cruises'),
    ('IAB20-13', 'Eastern Europe'),
    ('IAB20-14', 'Europe'),
    ('IAB20-15', 'France'),
    ('IAB20-16', 'Greece'),
    ('IAB20-17', 'Honeymoons/Getaways'),
    ('IAB20-18', 'Hotels'),
    ('IAB20-19', 'Italy'),
    ('IAB20-20', 'Japan'),
    ('IAB20-21', 'Mexico & Central America'),
    ('IAB20-22', 'National Parks'),
    ('IAB20-23', 'South America'),
    ('IAB20-24', 'Spas'),
    ('IAB20-25', 'Theme Parks'),
    ('IAB20-26', 'Traveling with Kids'),
    ('IAB20-27', 'United Kingdom'),
    ('IAB21', 'Real Estate'),
    ('IAB21-1', 'Apartments'),
    ('IAB21-2', 'Architects'),
    ('IAB21-3', 'Buying/Selling Homes'),
    ('IAB22', 'Shopping'),
    ('IAB22-1', 'Contests & Freebies'),
    ('IAB22-2', 'Couponing'),
    ('IAB22-3', 'Comparison'),
    ('IAB22-4', 'Engines'),
    ('IAB23', 'Religion & Spirituality'),
    ('IAB23-1', 'Alternative Religions'),
    ('IAB23-2', 'Atheism/Agnosticism'),
    ('IAB23-3', 'Buddhism'),
    ('IAB23-4', 'Catholicism'),
    ('IAB23-5', 'Christianity'),
    ('IAB23-6', 'Hinduism'),
    ('IAB23-7', 'Islam'),
    ('IAB23-8', 'Judaism'),
    ('IAB23-9', 'Latter-Day Saints'),
    ('IAB23-10', 'Pagan/Wiccan'),
    ('IAB24', 'Uncategorized'),
    ('IAB25', 'Non-Standard Content'),
    ('IAB25-1', 'Unmoderated UGC'),
    ('IAB25-2', 'Extreme Graphic/Explicit Violence'),
    ('IAB25-3', 'Pornography'),
    ('IAB25-4', 'Profane Content'),
    ('IAB25-5', 'Hate Content'),
    ('IAB25-6', 'Under Construction'),
    ('IAB25-7', 'Incentivized'),
    ('IAB26', 'Illegal Content'),
    ('IAB26-1', 'Illegal Content'),
    ('IAB26-2', 'Warez'),
    ('IAB26-3', 'Spyware/Malware'),
    ('IAB26-4', 'Copyright Infringement'),
]

MANAGE_CATEGORIES = [
    ('IAB99-1', 'Action'),
    ('IAB99-2', 'Adventure'),
    ('IAB99-3', 'Arcade'),
    ('IAB99-4', 'Board'),
    ('IAB99-5', 'Books'),
    ('IAB99-6', 'Business'),
    ('IAB99-7', 'Card'),
    ('IAB99-8', 'Casino'),
    ('IAB99-9', 'Dice'),
    ('IAB99-10', 'Educational'),
    ('IAB99-11', 'Family'),
    ('IAB99-12', 'Finance'),
    ('IAB99-13', 'Food&Drink'),
    ('IAB99-14', 'Health&Fitness'),
    ('IAB99-15', 'Kids'),
    ('IAB99-16', 'Lifestyle'),
    ('IAB99-17', 'Music'),
    ('IAB99-18', 'Navigation'),
    ('IAB99-19', 'News'),
    ('IAB99-20', 'Photo&Video'),
    ('IAB99-21', 'Puzzle'),
    ('IAB99-22', 'RolePlaying'),
    ('IAB99-23', 'SocialNetworking'),
    ('IAB99-24', 'Simulation'),
    ('IAB99-25', 'Sports'),
    ('IAB99-26', 'Strategy'),
    ('IAB99-27', 'Travel'),
    ('IAB99-28', 'Trivia'),
    ('IAB99-29', 'Utilities'),
    ('IAB99-30', 'Weather'),
    ('IAB99-31', 'Word'),
]

OTHER_IAB_CATEGORIES = [
    ('NEX1-101', 'Other'),
    ('NEX2-101', 'Automotive-General'),
    ('NEX2-102', 'Other'),
    ('NEX3-101', 'Gas/Energy'),
    ('NEX3-102', 'Other'),
    ('NEX4-101', 'Other'),
    ('NEX5-101', 'HigherEducation'),
    ('NEX5-102', 'Other'),
    ('NEX6-101', 'Other'),
    ('NEX7-101', 'Tobacco'),
    ('NEX7-102', 'ConsumerPackagedGoods(CPG)'),
    ('NEX7-103', 'Other'),
    ('NEX8-101', 'Liquor'),
    ('NEX8-102', 'QuickServeRestaurant(QSR)'),
    ('NEX8-103', 'Other'),
    ('NEX9-101', 'Action/AdventureGames'),
    ('NEX9-102', 'BingoGames'),
    ('NEX9-103', 'SportsGames'),
    ('NEX9-104', 'ContentDownloads&Subscriptions'),
    ('NEX9-105', 'CasinoGames'),
    ('NEX9-106', 'MatureGames'),
    ('NEX9-107', 'Surveys&Quizzes'),
    ('NEX9-108', 'Other'),
    ('NEX9-109', 'Gambling'),
    ('NEX10-101', 'Other'),
    ('NEX11-101', 'Election'),
    ('NEX11-102', 'Other'),
    ('NEX12-101', 'Newspapers'),
    ('NEX12-102', 'Other'),
    ('NEX13-101', 'Banking'),
    ('NEX13-102', 'Other'),
    ('NEX14-101', 'SocialNetworking&MessagingApps'),
    ('NEX14-102', 'Other'),
    ('NEX15-101', 'Other'),
    ('NEX16-101', 'Other'),
    ('NEX17-101', 'Other'),
    ('NEX18-101', 'Other'),
    ('NEX19-101', 'WirelessProviders'),
    ('NEX19-102', 'Telecom/CableProviders'),
    ('NEX19-103', 'Other'),
    ('NEX20-101', 'Resort&Casino'),
    ('NEX20-102', 'Navigation'),
    ('NEX20-103', 'Other'),
    ('NEX21-101', 'Other'),
    ('NEX22-101', 'Stores&DistributionChannels'),
    ('NEX22-102', 'Other'),
    ('NEX23-101', 'Other'),
    ('NEX25-101', 'AdvertiserUnknown'),
    ('NEX25-102', 'Other'),
    ('NEX26-101', 'Other'),
]

FLURRY_PERSONAS = [
    ('Business Travelers', 'Business Travelers'),
    ('Leisure Travelers', 'Leisure Travelers'),
    ('Social Influencers', 'Social Influencers'),
    ('Real Estate Followers', 'Real Estate Followers'),
    ('Auto Enthusiasts', 'Auto Enthusiasts'),
    ('Personal Finance Geeks', 'Personal Finance Geeks'),
    ('Casual & Social Gamers', 'Casual & Social Gamers'),
    ('Hardcore/Midcore Gamers', 'Hardcore/Midcore Gamers'),
    ('Sports Fans', 'Sports Fans'),
    ('Health & Fitness Enthusiasts', 'Health & Fitness Enthusiasts'),
    ('Fashionistas', 'Fashionistas'),
    ('Value Shoppers', 'Value Shoppers'),
    ('Entertainment Enthusiasts', 'Entertainment Enthusiasts'),
    ('Movie Lovers', 'Movie Lovers'),
    ('TV Lovers', 'TV Lovers'),
    ('Concert & Event lovers', 'Concert & Event lovers'),
    ('Music Lovers', 'Music Lovers'),
    ('Bookworms', 'Bookworms'),
    ('Tech & Gadget Enthusiasts', 'Tech & Gadget Enthusiasts'),
    ('Pet Owners', 'Pet Owners'),
    ('Home & Garden Pros', 'Home & Garden Pros'),
    ('Singles', 'Singles'),
    ('Catalog Shoppers', 'Catalog Shoppers'),
    ('Food & Dining Lovers', 'Food & Dining Lovers'),
    ('Business Professionals', 'Business Professionals'),
    ('New Moms', 'New Moms'),
    ('Parenting & Education', 'Parenting & Education'),
    ('News & Magazine Readers', 'News & Magazine Readers'),
    ('Photo & Video Enthusiasts', 'Photo & Video Enthusiasts'),
    ('Small Business Owners', 'Small Business Owners'),
    ('Moms', 'Moms'),
    ('Home Design Enthusiasts', 'Home Design Enthusiasts'),
    ('LGBT', 'LGBT'),
    ('Avid Runners', 'Avid Runners'),
    ('Slots Players', 'Slots Players'),
    ('American Football Fans', 'American Football Fans'),
    ('High Networth Individuals', 'High Networth Individuals'),
    ('Flight Intenders', 'Flight Intenders'),
    ('Mobile Payment Makers', 'Mobile Payment Makers'),
    ('Spanish Speakers', 'Spanish Speakers'),
    ('Engineering Enthusiasts', 'Engineering Enthusiasts'),
    ('Cat Lovers', 'Cat Lovers'),
]

US_REGIONS = [
    ("AL", "Alabama"),
    ("AK", "Alaska"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DE", "Delaware"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("HI", "Hawaii"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("KS", "Kansas"),
    ("KY", "Kentucky"),
    ("LA", "Louisiana"),
    ("ME", "Maine"),
    ("MD", "Maryland"),
    ("MA", "Massachusetts"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MT", "Montana"),
    ("NE", "Nebraska"),
    ("NV", "Nevada"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NY", "New York"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VT", "Vermont"),
    ("VA", "Virginia"),
    ("WA", "Washington"),
    ("WV", "West Virginia"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
    ("PR", "Puerto Rico"),
    ("VI", "U.S. Virgin Islands"),
    ("AS", "American Samoa"),
    ("GU", "Guam"),
]

COUNTRIES = [
    ("", ""),
    ("AFG", "Afghanistan"),
    ("ALB", "Albania"),
    ("DZA", "Algeria"),
    ("ASM", "American Samoa"),
    ("AND", "Andorra"),
    ("AGO", "Angola"),
    ("AIA", "Anguilla"),
    ("ATA", "Antarctica"),
    ("ATG", "Antigua and Barbuda"),
    ("ARG", "Argentina"),
    ("ARM", "Armenia"),
    ("ABW", "Aruba"),
    ("AUS", "Australia"),
    ("AUT", "Austria"),
    ("AZE", "Azerbaijan"),
    ("BHS", "Bahamas"),
    ("BHR", "Bahrain"),
    ("BGD", "Bangladesh"),
    ("BRB", "Barbados"),
    ("BLR", "Belarus"),
    ("BEL", "Belgium"),
    ("BLZ", "Belize"),
    ("BEN", "Benin"),
    ("BMU", "Bermuda"),
    ("BTN", "Bhutan"),
    ("BOL", "Bolivia"),
    ("BIH", "Bosnia and Herzegovina"),
    ("BWA", "Botswana"),
    ("BVT", "Bouvet Island"),
    ("BRA", "Brazil"),
    ("IOT", "British Indian Ocean Territory"),
    ("BRN", "Brunei"),
    ("BGR", "Bulgaria"),
    ("BFA", "Burkina Faso"),
    ("BDI", "Burundi"),
    ("KHM", "Cambodia"),
    ("CMR", "Cameroon"),
    ("CAN", "Canada"),
    ("CPV", "Cape Verde"),
    ("CYM", "Cayman Islands"),
    ("CAF", "Central African Republic"),
    ("TCD", "Chad"),
    ("CHL", "Chile"),
    ("CHN", "China"),
    ("CXR", "Christmas Island"),
    ("CCK", "Cocos (Keeling) Islands"),
    ("COL", "Colombia"),
    ("COM", "Comoros"),
    ("COG", "Congo (Brazzaville)"),
    ("COD", "Congo (Kinshasa)"),
    ("COK", "Cook Islands"),
    ("CRI", "Costa Rica"),
    ("CIV", "Cote d'Ivoire"),
    ("HRV", "Croatia"),
    ("CUB", "Cuba"),
    ("CYP", "Cyprus"),
    ("CZE", "Czech Republic"),
    ("DNK", "Denmark"),
    ("DJI", "Djibouti"),
    ("DMA", "Dominica"),
    ("DOM", "Dominican Republic"),
    ("ECU", "Ecuador"),
    ("EGY", "Egypt"),
    ("SLV", "El Salvador"),
    ("GNQ", "Equatorial Guinea"),
    ("ERI", "Eritrea"),
    ("EST", "Estonia"),
    ("ETH", "Ethiopia"),
    ("FLK", "Falkland Islands"),
    ("FRO", "Faroe Islands"),
    ("FJI", "Fiji"),
    ("FIN", "Finland"),
    ("FRA", "France"),
    ("GUF", "French Guiana"),
    ("PYF", "French Polynesia"),
    ("ATF", "French Southern Territories"),
    ("GAB", "Gabon"),
    ("GMB", "Gambia"),
    ("GEO", "Georgia"),
    ("DEU", "Germany"),
    ("GHA", "Ghana"),
    ("GIB", "Gibraltar"),
    ("GRC", "Greece"),
    ("GRL", "Greenland"),
    ("GRD", "Grenada"),
    ("GLP", "Guadeloupe"),
    ("GUM", "Guam"),
    ("GTM", "Guatemala"),
    ("GIN", "Guinea"),
    ("GNB", "Guinea-Bissau"),
    ("GUY", "Guyana"),
    ("HTI", "Haiti"),
    ("HMD", "Heard Island and McDonald Islands"),
    ("VAT", "Vatican"),
    ("HND", "Honduras"),
    ("HKG", "Hong Kong"),
    ("HUN", "Hungary"),
    ("ISL", "Iceland"),
    ("IND", "India"),
    ("IDN", "Indonesia"),
    ("IRN", "Iran"),
    ("IRQ", "Iraq"),
    ("IRL", "Ireland"),
    ("ISR", "Israel"),
    ("ITA", "Italy"),
    ("JAM", "Jamaica"),
    ("JPN", "Japan"),
    ("JOR", "Jordan"),
    ("KAZ", "Kazakhstan"),
    ("KEN", "Kenya"),
    ("KIR", "Kiribati"),
    ("PRK", "North Korea"),
    ("KOR", "South Korea"),
    ("KWT", "Kuwait"),
    ("KGZ", "Kyrgyzstan"),
    ("LAO", "Laos"),
    ("LVA", "Latvia"),
    ("LBN", "Lebanon"),
    ("LSO", "Lesotho"),
    ("LBR", "Liberia"),
    ("LBY", "Libya"),
    ("LIE", "Liechtenstein"),
    ("LTU", "Lithuania"),
    ("LUX", "Luxembourg"),
    ("MAC", "Macao"),
    ("MKD", "Macedonia"),
    ("MDG", "Madagascar"),
    ("MWI", "Malawi"),
    ("MYS", "Malaysia"),
    ("MDV", "Maldives"),
    ("MLI", "Mali"),
    ("MLT", "Malta"),
    ("MHL", "Marshall Islands"),
    ("MTQ", "Martinique"),
    ("MRT", "Mauritania"),
    ("MUS", "Mauritius"),
    ("MYT", "Mayotte"),
    ("MEX", "Mexico"),
    ("FSM", "Micronesia"),
    ("MDA", "Moldova"),
    ("MCO", "Monaco"),
    ("MNG", "Mongolia"),
    ("MNE", "Montenegro"),
    ("MSR", "Montserrat"),
    ("MAR", "Morocco"),
    ("MOZ", "Mozambique"),
    ("MMR", "Myanmar"),
    ("NAM", "Namibia"),
    ("NRU", "Nauru"),
    ("NPL", "Nepal"),
    ("NLD", "Netherlands"),
    ("ANT", "Netherlands Antilles"),
    ("NCL", "New Caledonia"),
    ("NZL", "New Zealand"),
    ("NIC", "Nicaragua"),
    ("NER", "Niger"),
    ("NGA", "Nigeria"),
    ("NIU", "Niue"),
    ("NFK", "Norfolk Island"),
    ("MNP", "Northern Mariana Islands"),
    ("NOR", "Norway"),
    ("OMN", "Oman"),
    ("PAK", "Pakistan"),
    ("PLW", "Palau"),
    ("PSE", "Palestinian Territory"),
    ("PAN", "Panama"),
    ("PNG", "Papua New Guinea"),
    ("PRY", "Paraguay"),
    ("PER", "Peru"),
    ("PHL", "Philippines"),
    ("PCN", "Pitcairn"),
    ("POL", "Poland"),
    ("PRT", "Portugal"),
    ("PRI", "Puerto Rico"),
    ("QAT", "Qatar"),
    ("REU", "Reunion"),
    ("ROU", "Romania"),
    ("RUS", "Russia"),
    ("RWA", "Rwanda"),
    ("SHN", "Saint Helena, Ascension and Tristan da Cunha"),
    ("KNA", "Saint Kitts and Nevis"),
    ("LCA", "Saint Lucia"),
    ("SPM", "Saint Pierre and Miquelon"),
    ("VCT", "Saint Vincent and the Grenadines"),
    ("WSM", "Samoa"),
    ("SMR", "San Marino"),
    ("STP", "Sao Tome and Principe"),
    ("SAU", "Saudi Arabia"),
    ("SEN", "Senegal"),
    ("SRB", "Serbia"),
    ("SYC", "Seychelles"),
    ("SLE", "Sierra Leone"),
    ("SGP", "Singapore"),
    ("SVK", "Slovakia"),
    ("SVN", "Slovenia"),
    ("SLB", "Solomon Islands"),
    ("SOM", "Somalia"),
    ("ZAF", "South Africa"),
    ("SGS", "South Georgia and the South Sandwich Islands"),
    ("ESP", "Spain"),
    ("LKA", "Sri Lanka"),
    ("SDN", "Sudan"),
    ("SUR", "Suriname"),
    ("SJM", "Svalbard and Jan Mayen"),
    ("SWZ", "Swaziland"),
    ("SWE", "Sweden"),
    ("CHE", "Switzerland"),
    ("SYR", "Syria"),
    ("TWN", "Taiwan"),
    ("TJK", "Tajikistan"),
    ("TZA", "Tanzania"),
    ("THA", "Thailand"),
    ("TLS", "Timor-Leste"),
    ("TGO", "Togo"),
    ("TKL", "Tokelau"),
    ("TON", "Tonga"),
    ("TTO", "Trinidad and Tobago"),
    ("TUN", "Tunisia"),
    ("TUR", "Turkey"),
    ("TKM", "Turkmenistan"),
    ("TCA", "Turks and Caicos Islands"),
    ("TUV", "Tuvalu"),
    ("UGA", "Uganda"),
    ("UKR", "Ukraine"),
    ("ARE", "United Arab Emirates"),
    ("USA", "United States"),
    ("UMI", "United States Minor Outlying Islands"),
    ("URY", "Uruguay"),
    ("UZB", "Uzbekistan"),
    ("VUT", "Vanuatu"),
    ("VEN", "Venezuela"),
    ("VNM", "Vietnam"),
    ("VGB", "Virgin Islands, British"),
    ("VIR", "Virgin Islands, U.S."),
    ("WLF", "Wallis and Futuna"),
    ("ESH", "Western Sahara"),
    ("YEM", "Yemen"),
    ("ZMB", "Zambia"),
    ("ZWE", "Zimbabwe"),
    ("ALA", "Aland Islands"),
    ("GGY", "Guernsey"),
    ("IMN", "Isle of Man"),
    ("JEY", "Jersey"),
    ("BLM", "Saint Barthelemy"),
    ("MAF", "Saint Martin (French part)"),
    ("GBR", "United Kingdom"),
    ("CUW", "Curacao"),
    ("SXM", "Sint Maarten (Dutch part)"),
    ("BES", "Bonaire, Saint Eustatius and Saba"),
]

US_REGION_DMA = [
    (743, "Anchorage, AK"),
    (745, "Fairbanks, AK"),
    (747, "Juneau, AK"),
    (606, "Dothan, AL"),
    (630, "Birmingham, AL"),
    (691, "Huntsville-Decatur (Florence), AL"),
    (698, "Montgomery (Selma), AL"),
    (686, "Mobile, AL-Pensacola, FL"),
    (522, "Columbus, GA"),
    (711, "Meridian, MS"),
    (524, "Atlanta, GA"),
    (673, "Columbus-Tupelo-West Point, MS"),
    (693, "Little Rock-Pine Bluff, AR"),
    (670, "Ft Smith-Springdale, AR"),
    (640, "Memphis, TN"),
    (734, "Jonesboro, AR"),
    (612, "Shreveport, LA"),
    (619, "Springfield, MO"),
    (628, "Monroe, LA-El Dorado, AR"),
    (789, "Tucson (Sierra Vista), AZ"),
    (753, "Phoenix, AZ"),
    (790, "Albuquerque-Santa Fe, NM"),
    (771, "Yuma, AZ-El Centro, CA"),
    (803, "Los Angeles, CA"),
    (807, "San Francisco-Oakland-San Jose, CA"),
    (862, "Sacramento-Stockton-Modesto, CA"),
    (866, "Fresno-Visalia, CA"),
    (825, "San Diego, CA"),
    (868, "Chico-Redding, CA"),
    (828, "Monterey-Salinas, CA"),
    (802, "Eureka, CA"),
    (855, "Santa Barbara-San Luis Obispo, CA"),
    (800, "Bakersfield, CA"),
    (811, "Reno, NV"),
    (804, "Palm Springs, CA"),
    (813, "Medford-Klamath Falls, OR"),
    (751, "Denver, CO"),
    (752, "Colorado Springs-Pueblo, CO"),
    (773, "Grand Junction-Montrose, CO"),
    (533, "Hartford & New Haven, CT"),
    (501, "New York, NY"),
    (511, "Washington, DC (Hagerstown, MD)"),
    (504, "Philadelphia, PA"),
    (576, "Salisbury, MD"),
    (592, "Gainesville, FL"),
    (534, "Orlando-Daytona Beach, FL"),
    (656, "Panama City, FL"),
    (539, "Tampa-St Petersburg (Sarasota), FL"),
    (571, "Ft. Myers-Naples, FL"),
    (561, "Jacksonville, FL"),
    (548, "West Palm Beach-Ft. Pierce, FL"),
    (528, "Miami-Ft. Lauderdale, FL"),
    (530, "Tallahassee, FL-Thomasville, GA"),
    (503, "Macon, GA"),
    (525, "Albany, GA"),
    (507, "Savannah, GA"),
    (520, "Augusta, GA"),
    (567, "Greenville-Spartanburg, SC"),
    (575, "Chattanooga, TN"),
    (744, "Honolulu, HI"),
    (679, "Des Moines-Ames, IA"),
    (631, "Ottumwa, IA-Kirksville, MO"),
    (637, "Cedar Rapids-Waterloo-Iowa City, IA"),
    (624, "Sioux City, IA"),
    (682, "Davenport,IA-Rock Island-Moline,IL"),
    (652, "Omaha, NE"),
    (611, "Rochester-Austin, MN-Mason City, IA"),
    (717, "Quincy, IL-Hannibal, MO-Keokuk, IA"),
    (725, "Sioux Falls(Mitchell), SD"),
    (758, "Idaho Falls-Pocatello, ID"),
    (881, "Spokane, WA"),
    (757, "Boise, ID"),
    (760, "Twin Falls, ID"),
    (770, "Salt Lake City, UT"),
    (609, "St. Louis, MO"),
    (602, "Chicago, IL"),
    (649, "Evansville, IN"),
    (648, "Champaign & Springfield-Decatur,IL"),
    (610, "Rockford, IL"),
    (632, "Paducah, KY-Harrisburg, IL"),
    (581, "Terre Haute, IN"),
    (675, "Peoria-Bloomington, IL"),
    (588, "South Bend-Elkhart, IN"),
    (527, "Indianapolis, IN"),
    (509, "Ft. Wayne, IN"),
    (515, "Cincinnati, OH"),
    (529, "Louisville, KY"),
    (582, "Lafayette, IN"),
    (678, "Wichita-Hutchinson, KS"),
    (605, "Topeka, KS"),
    (603, "Joplin, MO-Pittsburg, KS"),
    (616, "Kansas City, MO"),
    (722, "Lincoln & Hastings-Kearney, NE"),
    (671, "Tulsa, OK"),
    (638, "St. Joseph, MO"),
    (557, "Knoxville, TN"),
    (659, "Nashville, TN"),
    (541, "Lexington, KY"),
    (564, "Charleston-Huntington, WV"),
    (736, "Bowling Green, KY"),
    (531, "Tri-Cities, TN-VA"),
    (642, "Lafayette, LA"),
    (716, "Baton Rouge, LA"),
    (644, "Alexandria, LA"),
    (622, "New Orleans, LA"),
    (643, "Lake Charles, LA"),
    (506, "Boston, MA-Manchester, NH"),
    (521, "Providence, RI-New Bedford, MA"),
    (532, "Albany-Schenectady-Troy, NY"),
    (543, "Springfield-Holyoke, MA"),
    (512, "Baltimore, MD"),
    (508, "Pittsburgh, PA"),
    (500, "Portland-Auburn, ME"),
    (537, "Bangor, ME"),
    (552, "Presque Isle, ME"),
    (547, "Toledo, OH"),
    (540, "Traverse City-Cadillac, MI"),
    (563, "Grand Rapids-Kalamazoo, MI"),
    (513, "Flint-Saginaw-Bay City, MI"),
    (505, "Detroit, MI"),
    (583, "Alpena, MI"),
    (553, "Marquette, MI"),
    (551, "Lansing, MI"),
    (658, "Green Bay-Appleton, WI"),
    (676, "Duluth, MN-Superior, WI"),
    (724, "Fargo-Valley City, ND"),
    (613, "Minneapolis-St. Paul, MN"),
    (702, "La Crosse-Eau Claire, WI"),
    (737, "Mankato, MN"),
    (604, "Columbia-Jefferson City, MO"),
    (710, "Hattiesburg-Laurel, MS"),
    (718, "Jackson, MS"),
    (647, "Greenwood-Greenville, MS"),
    (746, "Biloxi-Gulfport, MS"),
    (756, "Billings, MT"),
    (754, "Butte-Bozeman, MT"),
    (762, "Missoula, MT"),
    (766, "Helena, MT"),
    (687, "Minot-Bismarck-Dickinson, ND"),
    (755, "Great Falls, MT"),
    (764, "Rapid City, SD"),
    (798, "Glendive, MT"),
    (560, "Raleigh-Durham (Fayetteville), NC"),
    (518, "Greensboro-Winston Salem, NC"),
    (544, "Norfolk-Portsmouth-Newport News,VA"),
    (517, "Charlotte, NC"),
    (545, "Greenville-New Bern-Washington, NC"),
    (550, "Wilmington, NC"),
    (570, "Florence-Myrtle Beach, SC"),
    (759, "Cheyenne, WY-Scottsbluff, NE"),
    (740, "North Platte, NE"),
    (523, "Burlington, VT-Plattsburgh, NY"),
    (765, "El Paso, TX"),
    (634, "Amarillo, TX"),
    (839, "Las Vegas, NV"),
    (565, "Elmira, NY"),
    (502, "Binghamton, NY"),
    (514, "Buffalo, NY"),
    (549, "Watertown, NY"),
    (555, "Syracuse, NY"),
    (538, "Rochester, NY"),
    (526, "Utica, NY"),
    (535, "Columbus, OH"),
    (510, "Cleveland-Akron (Canton), OH"),
    (542, "Dayton, OH"),
    (554, "Wheeling, WV-Steubenville, OH"),
    (536, "Youngstown, OH"),
    (597, "Parkersburg, WV"),
    (558, "Lima, OH"),
    (596, "Zanesville, OH"),
    (657, "Sherman, TX-Ada, OK"),
    (650, "Oklahoma City, OK"),
    (627, "Wichita Falls, TX & Lawton, OK"),
    (810, "Yakima-Pasco-Richland-Kennewick, WA"),
    (820, "Portland, OR"),
    (801, "Eugene, OR"),
    (821, "Bend, OR"),
    (574, "Johnstown-Altoona, PA"),
    (566, "Harrisburg-Lancaster-York, PA"),
    (516, "Erie, PA"),
    (577, "Wilkes Barre-Scranton, PA"),
    (519, "Charleston, SC"),
    (546, "Columbia, SC"),
    (639, "Jackson, TN"),
    (651, "Lubbock, TX"),
    (662, "Abilene-Sweetwater, TX"),
    (623, "Dallas-Ft. Worth, TX"),
    (636, "Harlingen-Weslaco-McAllen, TX"),
    (709, "Tyler-Longview(Nacogdoches), TX"),
    (600, "Corpus Christi, TX"),
    (618, "Houston, TX"),
    (633, "Odessa-Midland, TX"),
    (641, "San Antonio, TX"),
    (635, "Austin, TX"),
    (625, "Waco-Temple-Bryan, TX"),
    (692, "Beaumont-Port Arthur, TX"),
    (626, "Victoria, TX"),
    (661, "San Angelo, TX"),
    (749, "Laredo, TX"),
    (573, "Roanoke-Lynchburg, VA"),
    (556, "Richmond-Petersburg, VA"),
    (559, "Bluefield-Beckley-Oak Hill, WV"),
    (569, "Harrisonburg, VA"),
    (584, "Charlottesville, VA"),
    (819, "Seattle-Tacoma, WA"),
    (705, "Wausau-Rhinelander, WI"),
    (669, "Madison, WI"),
    (617, "Milwaukee, WI"),
    (598, "Clarksburg-Weston, WV"),
    (767, "Casper-Riverton, WY"),
]

CREATIVE_ATTRS = [
    (1, "Audio Ad (Auto Play)"),
    (2, "Audio Ad (User Initiated)"),
    (3, "Expandable (Automatic)"),
    (4, "Expandable (User Initiated - Click)"),
    (5, "Expandable (User Initiated - Rollover)"),
    (6, "In-Banner Video Ad (Auto Play)"),
    (7, "In-Banner Video Ad (User Initiated)"),
    (8, "Pop (e.g., Over, Under, or upon Exit)"),
    (9, "Provocative or Suggestive Imagery"),
    (10, "Shaky, Flashing, Flickering, Extreme Animation, Smileys"),
    (11, "Surveys"),
    (12, "Text Only"),
    (13, "User Interactive (e.g., Embedded Games)"),
    (14, "Windows Dialog or Alert Style"),
    (15, "Has audio on/off button"),
    (16, "Ad can be skipped (e.g., skip button on preroll video)"),
    (1001, "Aggressive"),
    (1002, "Very Aggressive"),
    (1003, "No Brand"),
    (2001, "MRAID 1.0"),
    (2002, "MRAID 2.0"),
]

CREATIVE_ATTRS_VIDEO_AUTO_PLAY = CREATIVE_ATTRS[5][0]
CREATIVE_ATTRS_USER_INTERACTIVE = CREATIVE_ATTRS[12][0]
CREATIVE_ATTRS_EXPANDABLE = CREATIVE_ATTRS[3][0]

OS_CHOICES = (
    ('iOS', 'iOS'),
    ('Android', 'Android'),
    ('Kindle', 'Kindle'),
)

ZONE_ORIENTATION_BOTH = 'both'
ZONE_ORIENTATION_CHOICES = (
    ('landscape', 'landscape'),
    ('portrait', 'portrait'),
    (ZONE_ORIENTATION_BOTH, 'both')
)

ZONE_STATUS_LIVE = 'live'
ZONE_STATUS_CHOICES = (
    (ZONE_STATUS_LIVE, 'live'),
    ('testing', 'testing'),
    ('paused', 'paused')
)

ZONE_SIZE_BLANK = ''
ZONE_SIZE_CHOICES = (
    (ZONE_SIZE_BLANK, ''),
    ('300x250', '300x250'),
    ('320x50', '320x50'),
    ('240x350', '240x350'),
    ('390x200', '390x200'),
    ('320x480', '320x480'),
    ('480x320', '480x320'),
    ('560x750', '560x750'),
    ('750x560', '750x560'),
    ('728x90', '728x90'),
    ('768x1024', '768x1024'),
    ('1024x768', '1024x768'),
)

ZONE_AD_TYPE_DISPLAY_VAST_VOXEL = 1
ZONE_AD_TYPE_CHOICES = (
    (ZONE_AD_TYPE_DISPLAY_VAST_VOXEL, 'Display Vast Voxel'),
    (2, 'Display Voxel'),
    (3, 'Rewarded Video'),
    (4, 'Rewarded Voxel'),
    (5, 'Rewarded Video and Voxel'),
    (6, 'Display Vast'),
    (7, 'Display Ad'),
)

COST_METHOD_BLANK = ''
COST_METHOD_REVSHARE = 'revshare'
COST_METHOD_CHOICES = (
    ('cpm', 'cpm'),
    (COST_METHOD_REVSHARE, 'revshare'),
    (COST_METHOD_BLANK, ''),
)

# Twitter
TW_PROMOTED_TWEETS = 'PROMOTED_TWEETS'
TW_PROMOTED_ACCOUNT = 'PROMOTED_ACCOUNT'
TW_MEDIA = 'MEDIA'
TW_PRODUCT_TYPES = (
    ('PROMOTED_TWEETS', 'PROMOTED_TWEETS'),
    ('PROMOTED_ACCOUNT', 'PROMOTED_ACCOUNT'),
    ('MEDIA', 'MEDIA'),
)

TW_PLACEMENTS = (
    ('ALL_ON_TWITTER', 'ALL_ON_TWITTER'),
    ('TWITTER_SEARCH', 'TWITTER_SEARCH'),
    ('TWITTER_TIMELINE', 'TWITTER_TIMELINE'),
    ('PUBLISHER_NETWORK', 'PUBLISHER_NETWORK'),
    ('TWITTER_PROFILE', 'TWITTER_PROFILE'),
)

TW_OBJECTIVES = (
    ('APP_ENGAGEMENTS', 'APP_ENGAGEMENTS'),
    ('APP_INSTALLS', 'APP_INSTALLS'),
    ('FOLLOWERS', 'FOLLOWERS'),
    ('LEAD_GENERATION', 'LEAD_GENERATION'),
    ('QUALIFIED_IMPRESSIONS', 'QUALIFIED_IMPRESSIONS'),
    ('TWEET_ENGAGEMENTS', 'TWEET_ENGAGEMENTS'),
    ('VIDEO_VIEWS', 'VIDEO_VIEWS'),
    ('VIDEO_VIEWS_PREROLL', 'VIDEO_VIEWS_PREROLL'),
    ('WEBSITE_CLICKS', 'WEBSITE_CLICKS'),
)

TW_BID_TYPES = (
    ('AUTO', 'AUTO'),
    ('MAX', 'MAX'),
    ('TARGET', 'TARGET'),
)

TW_BID_UNITS = (
    ('APP_CLICK', 'APP_CLICK'),
    ('APP_INSTALL', 'APP_INSTALL'),
    ('LINK_CLICK', 'LINK_CLICK'),
    ('VIEW', 'VIEW'),
    ('ENGAGEMENT', 'ENGAGEMENT'),
    ('LEAD', 'LEAD'),
    ('FOLLOW', 'FOLLOW'),
    ('CPC', 'CPC'),
    ('CPI', 'CPI'),
    ('CPE', 'CPE'),
    ('CPV', 'CPV'),
)

TW_CHARGE_BYS = TW_BID_UNITS

TW_OPTIMIZATIONS = (
    ('DEFAULT', 'DEFAULT'),
    ('WEBSITE_CONVERSIONS', 'WEBSITE_CONVERSIONS'),
)

TW_CARD_TYPE = (
    ('app_card', 'App Card'),
    ('image', 'Image'),
    ('video', 'Video'),
)

TW_CUSTOM_CTA = (
    ('INSTALL', 'INSTALL'),
    ('INSTALL_OPEN', 'INSTALL_OPEN'),
    ('PLAY', 'PLAY'),
    ('SHOP', 'SHOP'),
    ('BOOK', 'BOOK'),
    ('CONNECT', 'CONNECT'),
    ('ORDER', 'ORDER'),
)

CREATIVE_PRUNING_STATUS_CHOICES = [
    ('delete', 'Delete'),
    ('pause', 'Pause'),
]
